dist: trusty
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libsdl2-dev
    - sudo apt-get install -y libsdl2-ttf-dev
language: cpp
compiler:
    - gcc
script:
    make
