dist: trusty
sudo: required
# We handle git submodules ourselves
git:
    submodules: false
# We change the ssh urls to http urls
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - sudo apt-get update
    - sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
language: cpp
compiler:
    - gcc
script:
    make
